# Generated by Django 4.0.6 on 2022-07-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_patiets',
            new_name='is_patients',
        ),
    ]
