# Generated by Django 4.0.6 on 2022-07-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_patiets_user_is_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
